---
services:
  web:
    build: .
    command: python src/main.py
    ports:
      - "${host_port:-5000}:5000"
    env_file:
      - .env
    volumes:
      - storage:/app/storage
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          initial_sync: true

        - action: sync+restart
          path: ./src/config.yml
          target: /app/src/config.yml

        - action: rebuild
          path: ./pyproject.toml

        - action: rebuild
          path: ./uv.lock

        - action: rebuild
          path: ./Dockerfile

    mem_limit: 512m
    cpus: 0.5

volumes:
  storage:
