---
services:
  web:
    build: .
    command: python src/main.py
    ports:
      - "${host_port:-5000}:5000"
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          initial_sync: true
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock
        - action: rebuild
          path: ./src/config.yml
        - action: rebuild
          path: ./Dockerfile
